# Generated by Django 4.2.27 on 2025-12-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
