# Generated by Django 4.2.27 on 2025-12-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_habit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
