# Generated by Django 4.2.27 on 2025-12-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_habit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
